stages:
  - build
  # - deploy
before_script:
  - eval "$(ssh-agent -s)"
#   - ssh-add ~/.ssh/id_rsa
#   - ssh-keyscan -H '176.107.160.53' >> ~/.ssh/known_hosts

compile:
  stage: build
  script:
    # Переходим в папку с Go файлами
    - cd $PROJECTS_DIR/$REPOSITORY_NAME
    - composer update
    - cd laradock
    - docker-compose stop
# deploy:
#     stage: deploy
#     script:
# Переходим в папку с билдом () там лежит бинарник и папка public
# - cd $CI_PROJECT_DIR/build
# Используем утилиту sshpass для удаленного выполнения команд на VDS
# - sshpass -V
# - export SSHPASS=$USER_PASS
# Останавливаем сервис
# - sshpass -e ssh -o stricthostkeychecking=no $USER@$HOST systemctl stop $SERVICE_NAME
# Копируем новые файлы
# - sshpass -e scp -o stricthostkeychecking=no -r . $USER@$HOST:$TARGET_DIR_ON_HOST
# Перезапускаем сервис
# - sshpass -e ssh -o stricthostkeychecking=no $USER@$HOST systemctl restart $SERVICE_NAME
